# Generated by Django 6.0.2 on 2026-06-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "indexes": [models.Index(fields=["nombre"], name="idx_usuario_nombre")],
            },
        ),
        migrations.CreateModel(
            name="Tiquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ganador", "Ganador"),
                            ("perdedor", "Perdedor"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiquetes",
                        to="tickets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiquete",
                "verbose_name_plural": "Tiquetes",
                "db_table": "tiquetes",
                "indexes": [
                    models.Index(
                        fields=["usuario", "estado"], name="idx_tiquete_usuario_estado"
                    ),
                    models.Index(fields=["creado_en"], name="idx_tiquete_creado_en"),
                ],
            },
        ),
    ]
